version: '3'

services:
  tz-sandbox:
    image: oxheadalpha/flextesa:latest
    command: ["nairobibox", "start"]
    ports:
      - "20000:20000"
    environment:
      - block_time=2
  hardhat:
    image: ethereumoptimism/hardhat
    ports:
      - "8545:8545"