version: "3.8"

services:
  tz-sandbox:
    image: oxheadalpha/flextesa:latest
    command: ["mumbaibox", "start"]
    ports:
      - "20000:20000"
    environment:
      - block_time=2
  geth:
    image: ethereum/client-go
    # command: ["init", "/genesis.json"]
    ports:
      - "8545:8545"
    volumes:
      - ./genesis.json:/genesis.json:ro